LineLength:
  Enabled: true
  Max: 120

MethodLength:
  Max: 35

SpaceInsideParens:
  Enabled: false

Encoding:
  Enabled: false

ConstantName:
  Enabled: false

SingleSpaceBeforeFirstArg:
  Enabled: false

Documentation:
  Enabled: false

EmptyLinesAroundBody:
  Enabled: false

StringLiterals:
  Enabled: true

AllCops:
  Excludes:
    - bin/**
    - config/**
    - db/**
    - script/**
    - !ruby/regexp /rubocop_ignore\.rb$/