# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5431b49e509c04620141a81f8af67eb89f730837d7a44491c81e57be0a94ed934a5a65083421194afa86834d0d167e96e84bf1b1b018169b83886e99bb8c04a3

test:
  secret_key_base: d1cf423fe1f3d243ee67a56ef772194ebca005fce0c62a45c19611438f3be19a988d6c3b7e708a10758b60cafadd858354ca6fef28e75f7b57758cc2d058f290

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
